//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YSQ.core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YSQ.core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;SC04.DE&quot;,&quot;DBXF.SG&quot;,&quot;KORZ&quot;,&quot;LYTUR.SW&quot;,&quot;18442920.SG&quot;,&quot;3190701.SG&quot;,&quot;UKAG.L&quot;,&quot;X507.SW&quot;,&quot;C079.SW&quot;,&quot;DSUG.L&quot;,&quot;AUEUIH.SW&quot;,&quot;EEXF.L&quot;,&quot;IEGY.AS&quot;,&quot;EDC.MX&quot;,&quot;RGB.AX&quot;,&quot;IFNA.MX&quot;,&quot;CRDG.L&quot;,&quot;11058191.DU&quot;,&quot;UC24.L&quot;,&quot;HEA-A.TO&quot;,&quot;6AQQ.DE&quot;,&quot;JJT&quot;,&quot;M9SB.DE&quot;,&quot;SALU.MI&quot;,&quot;SSAC.L&quot;,&quot;EMH5.L&quot;,&quot;XBAT.DE&quot;,&quot;LRX1.MU&quot;,&quot;60RR.L&quot;,&quot;GLTR&quot;,&quot;VEFK.BE&quot;,&quot;VHY.AX&quot;,&quot;DBPS.DE&quot;,&quot;DBPP.SG&quot;,&quot;SAUS.L&quot;,&quot;KSBY-143.TA&quot;,&quot;IQQC.MU&quot;,&quot;IBCD.DU&quot;,&quot;O118.L&quot;,&quot;XDWD.F&quot;,&quot;20007265.DU&quot;,&quot;AMES.SG&quot;,&quot;DBX8.F&quot;,&quot;BKF&quot;,&quot;CCTN.SW&quot;,&quot;140700.KS&quot;,&quot;INDX-M25.TA&quot;,&quot;DAX.PA&quot;,&quot;CBUS5.SW&quot;,&quot;DX2Y.SG&quot;,&quot;DSUS.L&quot;,&q....
        /// </summary>
        internal static string GetAllEtfs {
            get {
                return ResourceManager.GetString("GetAllEtfs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;3BLW.DE&quot;,&quot;^NQG5300LMAUD&quot;,&quot;^DWGBS&quot;,&quot;5EDX.DE&quot;,&quot;^NQUSM2791JPYN&quot;,&quot;^NQUSM2723&quot;,&quot;^NQUSS9570EUR&quot;,&quot;^NQDMASPALCJPYT&quot;,&quot;ENVFN.NX&quot;,&quot;D4OA.DE&quot;,&quot;^NQUSB2357LMN&quot;,&quot;FTSEB.AT&quot;,&quot;^SBND&quot;,&quot;^RGNOT&quot;,&quot;Q01G.Z&quot;,&quot;^RAPJLTRUSD&quot;,&quot;^NQEURO5500GBP&quot;,&quot;14071968.SG&quot;,&quot;^NQUSB3577JPYN&quot;,&quot;SXAM13L.Z&quot;,&quot;^NQTHMC&quot;,&quot;^NQRU0001AUDT&quot;,&quot;^DUGCDF&quot;,&quot;^NQUSB8000LMT&quot;,&quot;WIISR2710.FGI&quot;,&quot;WIBEL8350.L&quot;,&quot;^DSLV&quot;,&quot;^NQNA1700LMAUD&quot;,&quot;WIPACXJA8630.FGI&quot;,&quot;^NQUSM3000GBP&quot;,&quot;CA12S.NX&quot;,&quot;^NQGR8000CADN&quot;,&quot;^NQDMMEA8500CADT&quot;,&quot;^NQTH0001GBP&quot;,&quot;^VINX3700SEKNI&quot;,&quot;^NQUSM3700JPY&quot;,&quot;^SP1500-251010&quot;,&quot;U [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetAllIndex {
            get {
                return ResourceManager.GetString("GetAllIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;GLE.PA&quot;,&quot;AUB.AX&quot;,&quot;GLRE&quot;,&quot;SFG&quot;,&quot;AMIC&quot;,&quot;GTS&quot;,&quot;LRE.L&quot;,&quot;EIG&quot;,&quot;AIZ&quot;,&quot;NHF.AX&quot;,&quot;PRA&quot;,&quot;TRUP&quot;,&quot;AFL&quot;,&quot;MIC.TO&quot;,&quot;CNO&quot;,&quot;UNM&quot;,&quot;FAC&quot;,&quot;SCRI&quot;,&quot;DCS.MU&quot;,&quot;XM8.F&quot;,&quot;XBTC&quot;,&quot;VISN&quot;,&quot;QXQ.AX&quot;,&quot;VEND&quot;,&quot;DNAX&quot;,&quot;IPG&quot;,&quot;YUME&quot;,&quot;PUB.PA&quot;,&quot;MSHF&quot;,&quot;SAX.BE&quot;,&quot;TRS.L&quot;,&quot;IDI&quot;,&quot;CL2.SG&quot;,&quot;XM8.SG&quot;,&quot;0205.HK&quot;,&quot;DEN.DU&quot;,&quot;RVUE&quot;,&quot;PHRM.L&quot;,&quot;RLOC&quot;,&quot;DCS.SG&quot;,&quot;OMC&quot;,&quot;DEC.PA&quot;,&quot;CNET&quot;,&quot;FUEL&quot;,&quot;NMED&quot;,&quot;SZMK&quot;,&quot;SPN.V&quot;,&quot;KITM&quot;,&quot;WPP.L&quot;,&quot;Y07.SI&quot;,&quot;ZCNV.PA&quot;,&quot;NOC&quot;,&quot;MTX.DE&quot;,&quot;RTN1.SG&quot;,&quot;EAD.DE&quot;,&quot;QY6.SG&quot;,&quot;NTH.BE&quot;,&quot;EAD.PA&....
        /// </summary>
        internal static string GetAllStocksDetail {
            get {
                return ResourceManager.GetString("GetAllStocksDetail", resourceCulture);
            }
        }
    }
}
